language: c

matrix:
  include:
    - compiler: gcc-4.4
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.4-multilib
    - compiler: gcc-4.4
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.4
    - compiler: gcc-4.6
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.6-multilib
    - compiler: gcc-4.6
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.6
    - compiler: gcc-4.7
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.7-multilib
    - compiler: gcc-4.7
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.7
    - compiler: gcc-4.8
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.8-multilib
    - compiler: gcc-4.8
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.8
    - compiler: gcc-4.9
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.9-multilib
    - compiler: gcc-4.9
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-4.9
    - compiler: gcc-5
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-5-multilib
    - compiler: gcc-5
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-5
    - compiler: gcc-6
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-6-multilib
    - compiler: gcc-6
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-6
    - compiler: gcc-7
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-7-multilib
    - compiler: gcc-7
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-7
    - compiler: gcc-8
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-8-multilib
    - compiler: gcc-8
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-8
    - compiler: clang-3.3
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.3
            - gcc-multilib
    - compiler: clang-3.3
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.3
    - compiler: clang-3.4
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.4
            - gcc-multilib
    - compiler: clang-3.4
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.4
    - compiler: clang-3.5
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.5
            - gcc-multilib
    - compiler: clang-3.5
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.5
    - compiler: clang-3.6
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.6
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.6
            - gcc-multilib
    - compiler: clang-3.6
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.6
          packages:
            - libreadline-dev
            - clang-3.6
    - compiler: clang-3.7
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.7
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.7
            - gcc-multilib
    - compiler: clang-3.7
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.7
          packages:
            - libreadline-dev
            - clang-3.7
    - compiler: clang-3.8
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.8
            - gcc-multilib
    - compiler: clang-3.8
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.8
    - compiler: clang-3.9
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.9
            - gcc-multilib
    - compiler: clang-3.9
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.9
    - compiler: clang-4.0
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-4.0
            - gcc-multilib
    - compiler: clang-4.0
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libreadline-dev
            - clang-4.0
    - compiler: clang-5.0
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-5.0
            - gcc-multilib
    - compiler: clang-5.0
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libreadline-dev
            - clang-5.0
    - compiler: clang-6.0
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-6.0
            - gcc-multilib
    - compiler: clang-6.0
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - clang-6.0
    - compiler: clang-7
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-7
            - gcc-multilib
    - compiler: clang-7
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - clang-7
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: gcc
      dist: xenial
      env: PLATFORM=x86
           DIST=xenial
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: xenial
      env: PLATFORM=x86_64
           DIST=xenial
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: gcc
      dist: xenial
      env: PLATFORM=x86
           DIST=xenial
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: gcc
      dist: xenial
      env: PLATFORM=x86_64
           DIST=xenial
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: precise
      env: PLATFORM=x86
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: xenial
      env: PLATFORM=x86
           DIST=xenial
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: xenial
      env: PLATFORM=x86_64
           DIST=xenial
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: precise
      env: PLATFORM=x86
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: clang
      dist: xenial
      env: PLATFORM=x86
           DIST=xenial
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
    - compiler: clang
      dist: xenial
      env: PLATFORM=x86_64
           DIST=xenial
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
    - compiler: tcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
            - tcc
    - compiler: tcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
            - tcc
    - compiler: tcc
      dist: xenial
      env: PLATFORM=x86_64
           DIST=xenial
      addons:
        apt:
          packages:
            - libreadline-dev
            - tcc
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x32
      addons:
        apt:
          packages:
            - libc6-dev-x32
            - gcc-multilib
    - compiler: powerpc-linux-gnu-gcc
      dist: trusty
      env: PLATFORM=powerpc
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu
            - libc6-dev-powerpc-cross
            - qemu-user
    - compiler: arm-linux-gnueabi-gcc
      dist: trusty
      env: PLATFORM=arm
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-dev-armel-cross
            - qemu-user
    - compiler: gcc
      if: (branch = master) AND (type != pull_request)
      env:
        - secure: "rH+rQS0W+0U3C/W/uRqJ8E5A3KrlbWaDRpZtdT1/SO0kEMnmuG2b0UvoadcIKOEXNHnQeZ3kPQbG2Wjfo/D6up0mXGZLXAvaJZozagxdfF2QPHSpvj2NDRLM71+UaKK/ksq3auPq+o3Y74FZOc4oBr7kPpr01H0pK8/2lljxS2daINRgFfcsaRhKNshtvHBn/KLgbwa5vEB/jadKBKM+mgAYE1sFv8P3yZ3+MzxygpurJ6enU6/9JITF5QgB11ybivYCbqoEf+IhzxgsmELz0zgL+PCVzTvrrNzpCT1UZJ35vWht5Yf7/AmK3sI/rMJm7TYswFKAc7NUbn80oIw6opp7sW1oFqMEHnHNLMNSljg8BwUrbH+y6+yV7sRfG6djCTYUYGYY9ZC2Ef4r3s3ZrRwHuBujZx/DOnFj0nd0AuvETNPkMWD1996bvSQ+WkfZ4JdW335/G61GdQv7kMTutWLKrlDquqxKM1AsoP1d99vCBzpEfRKyZjDUUSmnjdvZ/QgIDidGzH3vYFO81N39HjgKZlxH+oCuoX2ak3A6BrOT7t6mgEXnGM4H9vWhoKb7hseadBsR7YnbFSRmF2FDihEoIJ/BCPykGSZWzxTF94zC3WURI1C3HL0sAHGg3M620FgFj3M4Xkf0CPsmdsjwsnZg6TgVkYwAaKKP0HI2MFs="
      addons:
        apt:
          packages:
            - libreadline-dev
        coverity_scan:
          project:
            name: "pali/udftools"
            description: "Build submitted via Travis CI"
          notification_email: pali.rohar@gmail.com
          build_command_prepend: "./autogen.sh && ./configure"
          build_command: make
          branch_pattern: master

before_script:
  - if ! which "$CC" &>/dev/null; then export CC=${CC%%-*}; fi
  - export CFLAGS="-W -Wall -Werror -g"
  - if [ -z "$NOOPT" ]; then export CFLAGS="$CFLAGS -O2"; fi
  - if ! [[ "$CC" =~ "gcc" && "`$CC -dumpversion | sed 's/^\([0-9]\)\.\([0-9]\).*/\1\2/;'`" -lt 48 ]]; then export CFLAGS="$CFLAGS -pedantic"; fi
  - if [[ "$CC" =~ "gcc" && "`$CC -dumpversion | sed 's/^\([0-9]\)\.\([0-9]\).*/\1\2/;'`" = "48" ]]; then export CFLAGS="$CFLAGS -Wno-error=pedantic"; fi
  - if [[ "$CC" =~ "gcc" && "$CC" != "gcc-4.4" ]]; then export CFLAGS="$CFLAGS -Wno-error=unused-but-set-variable"; fi # needed for AC_PROG_CC_C99
  - if [[ "$CC" =~ "clang" ]]; then export CFLAGS="$CFLAGS -Wno-error=unused-function"; fi # -Werror=unused-function is broken on clang
  - case "$PLATFORM" in
      "x86")       export CFLAGS="-m32 $CFLAGS" ;;
      "x86_64"|"") ;;
      "x32")       export CFLAGS="-mx32 $CFLAGS"; export LDFLAGS="--static" ;;
      "powerpc")   export CONFIGURE_FLAGS="--host=powerpc-linux-gnu"; export LDFLAGS="--static"; export RUN=qemu-ppc ;;
      "arm")       export CONFIGURE_FLAGS="--host=arm-linux-gnueabi"; export LDFLAGS="--static"; export RUN=qemu-arm ;;
      *)           echo "Unsupported platform '$PLATFORM'"; exit 1 ;;
    esac

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh
  - ./configure $CONFIGURE_FLAGS
  - make

after_failure:
  - cat config.log
