language: c

compiler:
  - gcc
  - clang

env:
  - PLATFORM=x86    TESTS=
  - PLATFORM=x86_64 TESTS=
  - PLATFORM=x86    TESTS=--enable-tests TESTLEVEL=basic
  - PLATFORM=x86_64 TESTS=--enable-tests TESTLEVEL=basic
  - PLATFORM=x86    TESTS=--enable-tests TESTLEVEL=extra
  - PLATFORM=x86_64 TESTS=--enable-tests TESTLEVEL=extra

addons: &addons
  apt:
    packages:
      - libreadline-dev
      - libreadline-dev:i386
      - gcc-multilib
      - cmake

#matrix:
#  include:
#    - compiler: gcc
#      env:
#        - secure: "rH+rQS0W+0U3C/W/uRqJ8E5A3KrlbWaDRpZtdT1/SO0kEMnmuG2b0UvoadcIKOEXNHnQeZ3kPQbG2Wjfo/D6up0mXGZLXAvaJZozagxdfF2QPHSpvj2NDRLM71+UaKK/ksq3auPq+o3Y74FZOc4oBr7kPpr01H0pK8/2lljxS2daINRgFfcsaRhKNshtvHBn/KLgbwa5vEB/jadKBKM+mgAYE1sFv8P3yZ3+MzxygpurJ6enU6/9JITF5QgB11ybivYCbqoEf+IhzxgsmELz0zgL+PCVzTvrrNzpCT1UZJ35vWht5Yf7/AmK3sI/rMJm7TYswFKAc7NUbn80oIw6opp7sW1oFqMEHnHNLMNSljg8BwUrbH+y6+yV7sRfG6djCTYUYGYY9ZC2Ef4r3s3ZrRwHuBujZx/DOnFj0nd0AuvETNPkMWD1996bvSQ+WkfZ4JdW335/G61GdQv7kMTutWLKrlDquqxKM1AsoP1d99vCBzpEfRKyZjDUUSmnjdvZ/QgIDidGzH3vYFO81N39HjgKZlxH+oCuoX2ak3A6BrOT7t6mgEXnGM4H9vWhoKb7hseadBsR7YnbFSRmF2FDihEoIJ/BCPykGSZWzxTF94zC3WURI1C3HL0sAHGg3M620FgFj3M4Xkf0CPsmdsjwsnZg6TgVkYwAaKKP0HI2MFs="
#      addons:
#        <<: *addons
#        coverity_scan:
#          project:
#            name: "pali/udftools"
#            description: "Build submitted via Travis CI"
#          notification_email: pali.rohar@gmail.com
#          build_command_prepend: "./autogen.sh && ./configure"
#          build_command: make
#          branch_pattern: master

before_script:
  - cd ..
  - mkdir cmocka
  - cd cmocka
  - PTH=$(pwd)
  - cd ..
  - export PATH="$PTH:$PATH"
  - export LD_LIBRARY_PATH="$PTH/lib"
  - CFLAGS="-W -Wall -O2 -g -I$PTH/include/"
  - if [ "$PLATFORM" = "x86" ]; then CFLAGS="-m32 $CFLAGS"; fi
  - export CFLAGS
  - export LDFLAGS="-L$PTH/lib/"
  - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar xf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PTH -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make install
  - cd ../../udftools

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh $TESTS
  - ./configure $TESTS
  - make
  - if [ -n "$TESTS" ]; then ./udffsck/travis-tests.sh $TESTLEVEL; fi

